package org.steelhawks.subsystems.superstructure;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import edu.wpi.first.networktables.BooleanEntry;
import edu.wpi.first.networktables.BooleanPublisher;
import edu.wpi.first.networktables.DoubleEntry;
import edu.wpi.first.networktables.DoublePublisher;
import edu.wpi.first.networktables.DoubleSubscriber;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.StringEntry;
import edu.wpi.first.networktables.StringPublisher;
import org.littletonrobotics.junction.Logger;
import org.steelhawks.FieldConstants;
import org.steelhawks.Toggles;
import org.steelhawks.util.AllianceFlip;

/**
 * Receives a LUT generated by the shot-solver {@code /tuner} site over NetworkTables
 * and hot-loads it into {@link ShooterStructure} so the robot drives and shoots
 * exactly as normal, just with the pushed table live.
 *
 * <p>This is the primary tuning path; the legacy {@link ShooterTuner} (single-point
 * forced control) is left untouched. The applied table is volatile (RAM only) — a
 * reboot/redeploy restores {@link ShooterStructure#loadLUTSolved()}; just re-push.
 *
 * <p>Uses raw {@link NetworkTableInstance} topics (not AdvantageKit {@code
 * LoggedNetwork*}) so the on-wire names are exactly {@code /GeneratedLUTTuner/...}
 * and the browser client can match them and read robot-published echoes reliably.
 *
 * <h2>NT contract (all under {@code /GeneratedLUTTuner/})</h2>
 * Website → robot:
 * <ul>
 *   <li>{@code Payload} (string) — JSON table, see below.</li>
 *   <li>{@code Apply} (bool) — rising-edge pulse; robot consumes (resets to false).</li>
 *   <li>{@code Revert} (bool) — pulse; restores the baked LUT.</li>
 *   <li>{@code Enabled} (bool) — gate; apply/revert honored only when true.</li>
 *   <li>{@code ForceUseLut} (bool) — pulse; sets {@link Toggles#useLUT} true.</li>
 *   <li>{@code TargetDistanceMeters} (double) — align-helper setpoint.</li>
 * </ul>
 * Robot → website:
 * <ul>
 *   <li>{@code AppliedHash} (string) — {@link String#hashCode()} of the exact payload
 *       parsed and applied; the site goes green only when it matches what it sent.</li>
 *   <li>{@code Status} (string) — "OK" / "reverted" / "error: ...".</li>
 *   <li>{@code AppliedRows}, {@code AppliedMinDistance}, {@code AppliedMaxDistance}.</li>
 *   <li>{@code LiveDistanceMeters}, {@code DistanceErrorMeters} (live − target).</li>
 *   <li>{@code UseLut} (bool) — echo of {@link Toggles#useLUT}; warn the operator if off.</li>
 * </ul>
 *
 * <p>Payload shape:
 * <pre>
 * {"rows":[{"d":1.743,"flywheel":10.89,"hood":73,"tof":1.11,"close":8.66,"far":11.11}, ...]}
 * </pre>
 * Units mirror {@code loadLUTSolved}: flywheel/close/far are commanded wheel-surface
 * m/s, hood is degrees, tof is seconds. Distances must be strictly increasing.
 */
public class GeneratedLUTTuner {

    private static GeneratedLUTTuner instance;

    public static GeneratedLUTTuner getInstance() {
        if (instance == null) instance = new GeneratedLUTTuner();
        return instance;
    }

    private static final ObjectMapper MAPPER = new ObjectMapper();
    private static final String NS = "/GeneratedLUTTuner/";

    // inputs (website to robot). Apply/Revert/ForceUseLut are monotonic REQUEST
    // numbers (the site writes Date.now() each time), not boolean pulses: the robot
    // acts when the value changes and never writes them back, so there's no reset
    // contention across reconnects/sessions and a repeated push always re-fires.
    private final StringEntry payload;
    private final BooleanEntry enabled;
    private final DoubleEntry targetDistance;
    private final DoubleSubscriber applyReq;
    private final DoubleSubscriber revertReq;
    private final DoubleSubscriber forceUseLutReq;

    private double lastApplyReq;
    private double lastRevertReq;
    private double lastForceReq;

    // outputs (robot -> website)
    private final StringPublisher appliedHash;
    private final StringPublisher status;
    private final DoublePublisher appliedRows;
    private final DoublePublisher appliedMinDistance;
    private final DoublePublisher appliedMaxDistance;
    private final DoublePublisher liveDistance;
    private final DoublePublisher distanceError;
    private final BooleanPublisher useLut;
    // Read-only echo of the gate. The browser can't both subscribe and publish the
    // same NT topic via ntcore-ts (a subscribe announce trips the publisher flag and
    // breaks setValue), so the website writes Enabled and reads this mirror.
    private final BooleanPublisher enabledEcho;

    private GeneratedLUTTuner() {
        NetworkTableInstance nt = NetworkTableInstance.getDefault();

        payload = nt.getStringTopic(NS + "Payload").getEntry("");
        enabled = nt.getBooleanTopic(NS + "Enabled").getEntry(false);
        targetDistance = nt.getDoubleTopic(NS + "TargetDistanceMeters").getEntry(0.0);
        applyReq = nt.getDoubleTopic(NS + "ApplyRequest").subscribe(0.0);
        revertReq = nt.getDoubleTopic(NS + "RevertRequest").subscribe(0.0);
        forceUseLutReq = nt.getDoubleTopic(NS + "ForceUseLutRequest").subscribe(0.0);

        // Seed defaults so the topics exist immediately for the dashboard.
        payload.setDefault("");
        enabled.setDefault(false);
        targetDistance.setDefault(0.0);

        // Adopt the current request values so a value retained from a prior session
        // doesn't fire on boot — only a fresh write (new number) triggers.
        lastApplyReq = applyReq.get();
        lastRevertReq = revertReq.get();
        lastForceReq = forceUseLutReq.get();

        appliedHash = nt.getStringTopic(NS + "AppliedHash").publish();
        status = nt.getStringTopic(NS + "Status").publish();
        appliedRows = nt.getDoubleTopic(NS + "AppliedRows").publish();
        appliedMinDistance = nt.getDoubleTopic(NS + "AppliedMinDistance").publish();
        appliedMaxDistance = nt.getDoubleTopic(NS + "AppliedMaxDistance").publish();
        liveDistance = nt.getDoubleTopic(NS + "LiveDistanceMeters").publish();
        distanceError = nt.getDoubleTopic(NS + "DistanceErrorMeters").publish();
        useLut = nt.getBooleanTopic(NS + "UseLut").publish();
        enabledEcho = nt.getBooleanTopic(NS + "EnabledEcho").publish();

        appliedHash.set("");
        status.set("idle");
        appliedRows.set(0);
        appliedMinDistance.set(0);
        appliedMaxDistance.set(0);
        liveDistance.set(0);
        distanceError.set(0);
        useLut.set(Toggles.useLUT.get());
        enabledEcho.set(false);
    }

    public void periodic() {
        // Always publish the align-helper readout + useLUT echo, gate or not.
        try {
            double live = ShooterStructure.distanceToTarget(
                AllianceFlip.apply(FieldConstants.Hub.HUB_CENTER_3D));
            double target = targetDistance.get();
            liveDistance.set(live);
            distanceError.set(target > 0 ? live - target : 0.0);
            Logger.recordOutput("GeneratedLUTTuner/LiveDistanceMeters", live);
        } catch (Exception e) {
            // Distance needs an estimated pose / turret transform; never let it
            // break the loop while the robot is still coming up.
        }
        useLut.set(Toggles.useLUT.get());
        enabledEcho.set(enabled.get());

        double forceReqVal = forceUseLutReq.get();
        if (forceReqVal != lastForceReq) {
            lastForceReq = forceReqVal;
            Toggles.useLUT.set(true);
        }

        double applyReqVal = applyReq.get();
        double revertReqVal = revertReq.get();
        boolean wantApply = applyReqVal != lastApplyReq;
        boolean wantRevert = revertReqVal != lastRevertReq;
        lastApplyReq = applyReqVal;
        lastRevertReq = revertReqVal;
        if (!wantApply && !wantRevert) return;

        if (!enabled.get()) {
            setStatus("error: enable /GeneratedLUTTuner/Enabled on the robot first");
            return;
        }

        if (wantRevert) {
            ShooterStructure.loadLUTSolved();
            appliedHash.set("");
            appliedRows.set(0);
            setStatus("reverted to baked LUT");
            return;
        }

        applyPayload(payload.get());
    }

    private void applyPayload(String json) {
        if (json == null || json.isBlank()) {
            setStatus("error: empty payload");
            return;
        }
        final double[] dist, flywheel, hood, tof, close, far;
        try {
            JsonNode root = MAPPER.readTree(json);
            JsonNode rows = root.get("rows");
            if (rows == null || !rows.isArray() || rows.size() < 2) {
                setStatus("error: payload needs a 'rows' array with >= 2 entries");
                return;
            }
            int n = rows.size();
            dist = new double[n];
            flywheel = new double[n];
            hood = new double[n];
            tof = new double[n];
            close = new double[n];
            far = new double[n];
            for (int i = 0; i < n; i++) {
                JsonNode r = rows.get(i);
                dist[i] = r.path("d").asDouble(Double.NaN);
                flywheel[i] = r.path("flywheel").asDouble(Double.NaN);
                hood[i] = r.path("hood").asDouble(Double.NaN);
                tof[i] = r.path("tof").asDouble(Double.NaN);
                close[i] = r.path("close").asDouble(Double.NaN);
                far[i] = r.path("far").asDouble(Double.NaN);
            }
        } catch (Exception e) {
            setStatus("error: bad JSON — " + e.getMessage());
            return;
        }

        try {
            // Validates before mutating; on throw the active maps are untouched.
            ShooterStructure.applyExternalLUT(dist, flywheel, hood, tof, close, far);
        } catch (IllegalArgumentException e) {
            setStatus("error: " + e.getMessage());
            return;
        }

        appliedHash.set(String.valueOf(json.hashCode()));
        appliedRows.set(dist.length);
        appliedMinDistance.set(dist[0]);
        appliedMaxDistance.set(dist[dist.length - 1]);
        setStatus("OK");
        System.out.printf("[GeneratedLUTTuner] Applied %d-row LUT, dist %.3f..%.3f m%n",
            dist.length, dist[0], dist[dist.length - 1]);
    }

    private void setStatus(String s) {
        status.set(s);
        Logger.recordOutput("GeneratedLUTTuner/Status", s);
    }
}
