package org.steelhawks.subsystems.superstructure;

import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.geometry.Pose3d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.geometry.Translation3d;
import edu.wpi.first.math.interpolation.InterpolatingDoubleTreeMap;
import edu.wpi.first.math.interpolation.InterpolatingTreeMap;
import edu.wpi.first.math.interpolation.InverseInterpolator;
import edu.wpi.first.math.util.Units;
import org.littletonrobotics.junction.Logger;
import org.littletonrobotics.junction.networktables.LoggedNetworkNumber;
import org.steelhawks.*;
import org.steelhawks.Constants.RobotConstants;
import org.steelhawks.RobotState.AimState;
import org.steelhawks.util.AllianceFlip;

import static edu.wpi.first.units.Units.Meters;

public class ShooterStructure {

    private static final InterpolatingDoubleTreeMap shootingTimeOfFlightMap =
        new InterpolatingDoubleTreeMap();
    private static final InterpolatingDoubleTreeMap shootingFlywheelVelocityMap =
        new InterpolatingDoubleTreeMap();
    private static final InterpolatingTreeMap<Double, Rotation2d> shootingHoodAngleMap =
        new InterpolatingTreeMap<>(InverseInterpolator.forDouble(), Rotation2d::interpolate);

    // Envelope band: min/max commanded wheel m/s that still scores at a given
    // distance, generated by shot-solver. Only populated by LUTs that emit the
    // envelope (loadLUTSolved). When empty, the band gate falls back to the
    // symmetric velocity tolerance.
    private static final InterpolatingDoubleTreeMap shootingFlywheelVelocityCloseMap =
        new InterpolatingDoubleTreeMap();
    private static final InterpolatingDoubleTreeMap shootingFlywheelVelocityFarMap =
        new InterpolatingDoubleTreeMap();

    private static final LoggedNetworkNumber lutDistanceOffsetMeters =
        new LoggedNetworkNumber("ShooterStructure/LUTDistanceOffsetMeters", Units.feetToMeters(0.0)); // 1.95ft is what we had on the field

    private static double minShootDistance;
    private static double maxShootDistance;
    // True when the active LUT populated the envelope band maps (loadLUTSolved does).
    private static boolean hasEnvelopeBand = false;

    public record ProjectileData(double exitVelocity, double hoodAngle, Translation3d target) {}
    public record MovingShotSolution(
        double exitVelocity,
        double hoodAngleRad,
        Rotation2d turretAngle,
        Translation3d virtualTarget,
        double timeOfFlight
    ) {}
    public static final ProjectileData kNoSolution = new ProjectileData(Double.NaN, Double.NaN, new Translation3d());
    private static final double G = 9.81;

    static {
        loadLUTSolved();
    }

    public static boolean isNoSolution(ProjectileData data) {
        return data == null || Double.isNaN(data.exitVelocity()) || Double.isNaN(data.hoodAngle());
    }

    public static double calculateTimeOfFlight(double v, double theta, double x, double deltaH) {
        return calculateTimeOfFlight(v, theta, x, deltaH, true);
    }

    /**
     * @param useLutIfEnabled Pass false to force kinematic TOF even when the LUT toggle is on.
     *                        The TOF LUT is calibrated against hub shots; ferry shots (much
     *                        higher arc) must skip it.
     */
    public static double calculateTimeOfFlight(double v, double theta, double x, double deltaH, boolean useLutIfEnabled) {
        // rearranged 0.5*g*t^2 - v*sin(theta)*t + deltaH = 0
        if (useLutIfEnabled && Toggles.useLUT.get() && !Toggles.useKinematicsTOF.get()) {
            return shootingTimeOfFlightMap.get(MathUtil.clamp(x, minShootDistance, maxShootDistance));
        }
        double a = 0.5 * G;
        double b = -v * Math.sin(theta);
        double c = deltaH;
        double discriminant = b * b - 4 * a * c;
        if (discriminant < 0) return Double.NaN;
        double t1 = (-b + Math.sqrt(discriminant)) / (2 * a);
        double t2 = (-b - Math.sqrt(discriminant)) / (2 * a);
        return (t1 > 0) ? t1 : t2;
    }

    public static double angularToLinearVelocity(double angularVelocityRadPerSec, double radius) {
        return angularVelocityRadPerSec * radius;
    }

    /**
     * True when the active LUT carries an envelope band (close/far velocity maps).
     * loadLUTSolved populates these; the hand-tuned hard/soft LUTs do not.
     */
    public static boolean hasVelocityBand() {
        return hasEnvelopeBand;
    }

    /**
     * Envelope band edges as ratios relative to the LUT's centroid velocity at the
     * given distance: {closeRatio, farRatio}. Multiply by the actually-commanded
     * flywheel speed to get the valid band in the same units — this carries through
     * every multiplier (redbull, ferry, auton) applied to the target.
     *
     * @return {closeRatio, farRatio}, or null if no band data / degenerate target.
     */
    public static double[] getVelocityBandRatios(double distance) {
        if (!hasVelocityBand()) return null;
        double d = MathUtil.clamp(distance, minShootDistance, maxShootDistance);
        double target = shootingFlywheelVelocityMap.get(d);
        if (target <= 1e-6) return null;
        double close = shootingFlywheelVelocityCloseMap.get(d);
        double far = shootingFlywheelVelocityFarMap.get(d);
        return new double[] {close / target, far / target};
    }

    public static double linearToAngularVelocity(double linearVelocityMetersPerSec, double radius) {
        return (linearVelocityMetersPerSec) / radius;
    }

    public static double distanceToTarget(Translation3d target) {
        return distanceToTarget(target, getTurretTranslation());
    }

    private static double distanceToTarget(Translation3d target, Translation2d turretXY) {
        return turretXY.getDistance(target.toTranslation2d());
    }

    /** Computes the turret's field-frame XY position from the current estimated pose. */
    static Translation2d getTurretTranslation() {
        return new Pose3d(RobotState.getInstance().getEstimatedPose())
            .transformBy(RobotConstants.ROBOT_TO_TURRET)
            .toPose2d()
            .getTranslation();
    }

    /**
     * Returns the turret height above the field floor in meters.
     */
    private static double turretHeightAboveField() {
        return RobotConstants.ROBOT_TO_TURRET.getZ();
    }

    public static class Static {

        public static ProjectileData calculateShot(Translation3d target, Translation3d predictedTarget) {
            return calculateShot(target, predictedTarget, false);
        }

        public static ProjectileData calculateShot(
            Translation3d actualTarget, Translation3d predictedTarget, boolean isFixedPitch
        ) {
            return calculateShot(actualTarget, predictedTarget, isFixedPitch, -1.0);
        }

        /**
         * Same as {@link #calculateShot} but accepts a pre-computed distance to avoid
         * recomputing the Pose3d turret transform chain. Pass -1 to compute it fresh.
         */
        public static ProjectileData calculateShot(
            Translation3d actualTarget, Translation3d predictedTarget, boolean isFixedPitch, double precomputedDist
        ) {
            if (isFixedPitch) {
                return calculateShotFixedPitch(actualTarget, predictedTarget);
            }
            double rawDist = precomputedDist >= 0 ? precomputedDist : distanceToTarget(predictedTarget);
            double x_dist = MathUtil.clamp(rawDist, minShootDistance, maxShootDistance);
            if (Toggles.useLUT.getAsBoolean()) {
                double lutDist = MathUtil.clamp(rawDist + lutDistanceOffsetMeters.get(), minShootDistance, maxShootDistance);
                return new ProjectileData(
                    shootingFlywheelVelocityMap.get(lutDist),
                    shootingHoodAngleMap.get(lutDist).getRadians(),
                    predictedTarget);
            }
            double y_dist = predictedTarget
                .getMeasureZ()
                .minus(RobotConstants.ROBOT_TO_TURRET.getMeasureZ()).in(Meters);
            // When actualTarget == predictedTarget (the SOTM loop case), r simplifies to FUNNEL_RADIUS
            // Use precomputedDist to avoid a second distanceToTarget() call
            double actualDist = precomputedDist >= 0 ? precomputedDist : distanceToTarget(actualTarget);
            double r = FieldConstants.Hub.FUNNEL_RADIUS
                * x_dist
                / actualDist;
            double h = FieldConstants.Hub.FUNNEL_HEIGHT + FieldConstants.Hub.DISTANCE_ABOVE_FUNNEL_TO_CLEAR;
            double A1 = x_dist * x_dist;
            double B1 = x_dist;
            double D1 = y_dist;
            double A2 = -x_dist * x_dist + (x_dist - r) * (x_dist - r);
            double B2 = -r;
            double D2 = h;
            double Bm = -B2 / B1;
            double A3 = Bm * A1 + A2;
            double D3 = Bm * D1 + D2;
            double a = D3 / A3;
            double b = (D1 - A1 * a) / B1;
            double theta = Math.atan(b);
            double v0 = Math.sqrt(-G / (2 * a * (Math.cos(theta)) * (Math.cos(theta))));
            if (Double.isNaN(v0) || Double.isNaN(theta)) {
                v0 = 0;
                theta = 0;
            }
            return new ProjectileData(
                v0,
                theta,
                predictedTarget);
        }

        /**
         * Computes a ballistic launch solution for a shooter with a fixed pitch angle.
         *
         * @param actualTarget    The real hub target.
         * @param predictedTarget Used for shooting on the move.
         * @return ProjectileData, or kNoSolution if the fixed angle cannot clear the funnel or reach the target.
         */
        private static ProjectileData calculateShotFixedPitch(
            Translation3d actualTarget, Translation3d predictedTarget
        ) {
            final double theta = RobotConstants.FIXED_SHOOTER_ANGLE;
            double cosTheta = Math.cos(theta);
            double tanTheta = Math.tan(theta);
            double turretH = turretHeightAboveField();
            double x = distanceToTarget(predictedTarget);
            double y = predictedTarget.getZ() - turretH;
            double denom = 2 * cosTheta * cosTheta * (x * tanTheta - y);
            if (denom <= 0) {
                return kNoSolution;
            }
            double v0 = Toggles.useLUT.get() ? shootingFlywheelVelocityMap.get(x) : Math.sqrt(G * x * x / denom);
            if (Double.isNaN(v0) || Double.isInfinite(v0)) {
                return kNoSolution;
            }
            double r = FieldConstants.Hub.FUNNEL_RADIUS * x / distanceToTarget(actualTarget);
            double xFunnel = x - r;
            double requiredHeight = (FieldConstants.Hub.FUNNEL_HEIGHT
                + FieldConstants.Hub.DISTANCE_ABOVE_FUNNEL_TO_CLEAR)
                - turretH;
            double yAtFunnel = xFunnel * tanTheta
                - (G * xFunnel * xFunnel) / (2.0 * v0 * v0 * cosTheta * cosTheta);
            if (yAtFunnel < requiredHeight) {
                return kNoSolution;
            }
            return new ProjectileData(v0, theta, predictedTarget);
        }

        public static ProjectileData calculateFerryShot(Translation2d actualTarget) {
            double x = distanceToTarget(new Translation3d(actualTarget.getX(), actualTarget.getY(), 0.0));
            double y = -turretHeightAboveField(); // ferry shot is on the ground so simplifies to this from 0 - turret_height

            double theta = Math.PI / 4.0;
            double cos = Math.cos(theta);
            double denom = 2.0 * cos * cos * (x * Math.tan(theta) - y);
            double v0 = Math.sqrt(G * x * x / denom);

            return new ProjectileData(v0, theta, new Translation3d(actualTarget.getX(), actualTarget.getY(), 0.0));
        }

        public static Translation2d calculateFerryShotSetpoint() {
            double robotYBlue = AllianceFlip.shouldFlip()
                ? FieldConstants.FIELD_WIDTH - RobotState.getInstance().getEstimatedPose().getY()
                : RobotState.getInstance().getEstimatedPose().getY();

            double offset = FieldConstants.Ferrying.DISTANCE_OFFSET;
            Translation2d segEnd = (robotYBlue < FieldConstants.FIELD_WIDTH / 2.0)
                ? FieldConstants.Ferrying.MID_LINE.minus(new Translation2d(0.0, offset))
                : FieldConstants.Ferrying.MID_LINE.plus(new Translation2d(0.0, offset));
            Translation2d segStart = (robotYBlue < FieldConstants.FIELD_WIDTH / 2.0)
                ? FieldConstants.Ferrying.START_LINE
                : FieldConstants.Ferrying.END_LINE;

            return AllianceFlip.apply(FieldConstants.getClosestPointOnLine(segStart, segEnd));
        }
    }

    public static class Moving {
        
        public static MovingShotSolution solveMovingShot(
            Translation3d actualTarget,
            Translation3d robotVelocity,
            Translation3d fieldAcceleration,
            Rotation2d robotHeading,
            double chassisOmegaRadPerSec,
            int maxIterations,
            double timeTolerance,
            double tofSpeedScale
        ) {
            boolean isFerry = RobotState.getInstance().getAimState().equals(AimState.FERRY);
            // Correct the LUT time-of-flight (hub shots only) for the actual launch
            // speed. The TOF LUT is calibrated at the commanded setpoint; if the
            // wheel fires off-setpoint (band gate during spin-up / sag) the real
            // flight time differs, and the turret lead would otherwise be wrong.
            // tofSpeedScale = setpoint/measured ≈ 1 when settled, so this is a no-op
            // for a steady-state shot. Ferry uses a kinematic TOF and is left alone.
            double tofScale = isFerry ? 1.0 : tofSpeedScale;
            Translation2d turretXY = getTurretTranslation();
            // add turrets tangential velocity from chassis rotation.
            // for a point at (dx, dy) in robot frame rotating at omega rad/s:
            //v = (-omega*dy, omega*dx) cross product
            double turretDx = RobotConstants.ROBOT_TO_TURRET.getX();
            double turretDy = RobotConstants.ROBOT_TO_TURRET.getY();
            Translation2d fieldRelativeVelocity =
                new Translation2d(
                    robotVelocity.getX() + (-chassisOmegaRadPerSec * turretDy),
                    robotVelocity.getY() + (chassisOmegaRadPerSec * turretDx)) // omega could be negative
                .rotateBy(robotHeading);

            // Launch latency: aim commits "now" but the ball doesn't leave for D seconds.
            // The hub is stationary, so the virtual target relative to the current turret
            // position (turretXY) is:
            //   vt = hub - v*(D + TOF) - a*D*TOF - 0.5*a*D^2
            // derived from: launch_pos = current + v*D + 0.5*a*D^2 ; v_launch = v + a*D ;
            // virtual target from launch = hub - v_launch * TOF ; rebased to current.
            // Set D=0 to disable latency compensation.
            final double D = Constants.SOTMConstants.LAUNCH_LATENCY_SECONDS.get();
            double accelX = fieldAcceleration.getX();
            double accelY = fieldAcceleration.getY();

            double deltaH = actualTarget.getZ() - turretHeightAboveField();
            double velX = fieldRelativeVelocity.getX();
            double velY = fieldRelativeVelocity.getY();
            // Position-only offset (independent of TOF): -v*D - 0.5*a*D^2
            double posOffsetX = -velX * D - 0.5 * accelX * D * D;
            double posOffsetY = -velY * D - 0.5 * accelY * D * D;
            Translation3d virtualTarget = actualTarget;
            double rawDist = turretXY.getDistance(actualTarget.toTranslation2d());
            double virtualDist = MathUtil.clamp(rawDist, minShootDistance, maxShootDistance);
            var projectile =
                isFerry
                    ? Static.calculateFerryShot(actualTarget.toTranslation2d())
                    : Static.calculateShot(actualTarget, actualTarget, false, rawDist);
            double v = projectile.exitVelocity();
            double theta = projectile.hoodAngle();
            double tGuess = calculateTimeOfFlight(v, theta, virtualDist, deltaH, !isFerry) * tofScale;
            int convergedAt = maxIterations;
            for (int i = 0; i < maxIterations; i++) {
                double dragC = Constants.SOTMConstants.DRAG_COEFFICIENT.get();
                double driftTOF = dragC > 1e-6
                    ? (1.0 - Math.exp(-dragC * tGuess)) / dragC
                    : tGuess;
                double tofOffsetX = -velX * driftTOF - accelX * D * tGuess;
                double tofOffsetY = -velY * driftTOF - accelY * D * tGuess;
                virtualTarget = new Translation3d(
                    actualTarget.getX() + posOffsetX + tofOffsetX,
                    actualTarget.getY() + posOffsetY + tofOffsetY,
                    actualTarget.getZ());
                rawDist = turretXY.getDistance(virtualTarget.toTranslation2d());
                virtualDist = MathUtil.clamp(rawDist, minShootDistance, maxShootDistance);
                projectile = isFerry
                    ? Static.calculateFerryShot(virtualTarget.toTranslation2d())
                    : Static.calculateShot(virtualTarget, virtualTarget, false, rawDist);
                v = projectile.exitVelocity();
                theta = projectile.hoodAngle();
                double newTof = calculateTimeOfFlight(v, theta, virtualDist, deltaH, !isFerry) * tofScale;

                // Newton step: f(t) = LUT(d(t)) - t = 0
                // f'(t) estimated via central finite difference on the TOF function,
                // chained through the virtual distance which itself depends on t.
                // dPrime = d/dt [ LUT(d(t)) ] = (dLUT/dd) * (dd/dt)
                // dd/dt = d/dt ||hub - v*g(t)|| = -(v . (hub - v*g(t))) / d * e^(-c*t)
                // where e^(-c*t) = d/dt g(t)
                final double H = 0.005; // 5ms finite difference step
                double tofHigh = calculateTimeOfFlight(
                    projectile.exitVelocity(), projectile.hoodAngle(),
                    MathUtil.clamp(
                        turretXY.getDistance(new Translation3d(
                            actualTarget.getX() + posOffsetX + (-velX * (dragC > 1e-6 ? (1.0 - Math.exp(-dragC * (tGuess + H))) / dragC : (tGuess + H))),
                            actualTarget.getY() + posOffsetY + (-velY * (dragC > 1e-6 ? (1.0 - Math.exp(-dragC * (tGuess + H))) / dragC : (tGuess + H))),
                            actualTarget.getZ()).toTranslation2d()),
                        minShootDistance, maxShootDistance),
                    deltaH, !isFerry) * tofScale;
                double tofLow = calculateTimeOfFlight(
                    projectile.exitVelocity(), projectile.hoodAngle(),
                    MathUtil.clamp(
                        turretXY.getDistance(new Translation3d(
                            actualTarget.getX() + posOffsetX + (-velX * (dragC > 1e-6 ? (1.0 - Math.exp(-dragC * (tGuess - H))) / dragC : (tGuess - H))),
                            actualTarget.getY() + posOffsetY + (-velY * (dragC > 1e-6 ? (1.0 - Math.exp(-dragC * (tGuess - H))) / dragC : (tGuess - H))),
                            actualTarget.getZ()).toTranslation2d()),
                        minShootDistance, maxShootDistance),
                    deltaH, !isFerry) * tofScale;
                double dPrime = (tofHigh - tofLow) / (2.0 * H);
                // f(t) = newTof - tGuess, f'(t) = dPrime - 1
                double f = newTof - tGuess;
                double fPrime = dPrime - 1.0;
                double nextTof;
                if (Math.abs(fPrime) > 0.01) {
                    nextTof = tGuess - f / fPrime;
                } else {
                    nextTof = newTof; // fallback to fixed-point if derivative is degenerate
                }
                nextTof = MathUtil.clamp(nextTof, 0.05, 2.0);
                if (Math.abs(nextTof - tGuess) < timeTolerance) {
                    convergedAt = i + 1;
                    tGuess = nextTof;
                    break;
                }
                tGuess = nextTof;
            }

            Logger.recordOutput("SOTM/VirtualTarget", virtualTarget);
            Logger.recordOutput("SOTM/VirtualDistance", virtualDist);
            Logger.recordOutput("SOTM/TOF", tGuess);
            Logger.recordOutput("SOTM/TofScaleApplied", tofScale);
            Logger.recordOutput("SOTM/LaunchLatency", D);
            Logger.recordOutput("SOTM/ExitVelocity", v);
            Logger.recordOutput("SOTM/HoodAngleDeg", Math.toDegrees(theta));
            Logger.recordOutput("SOTM/ConvergedIterations", convergedAt);

            double fieldRelativeAngle = Math.atan2(
                virtualTarget.getY() - turretXY.getY(),
                virtualTarget.getX() - turretXY.getX());
            double turretMountYaw = RobotConstants.ROBOT_TO_TURRET.getRotation().getZ();
            double turretRelativeAngle = MathUtil.angleModulus(
                fieldRelativeAngle - robotHeading.getRadians() - turretMountYaw);
            Logger.recordOutput("SOTM/TurretRelativeAngleDeg", Math.toDegrees(turretRelativeAngle));
            return new MovingShotSolution(v, theta, Rotation2d.fromRadians(turretRelativeAngle), virtualTarget, tGuess);
        }
    }

    // Generated by shot-solver. Values are COMMANDED wheel-surface m/s
    // (ideal ball exit ÷ η_slip · wear). If you re-tune the slip slider,
    // regenerate — the offset is uniform across distances.
    //
    // Generation parameters:
    //   placement bias    0.91 (back rim)
    //   slip η            0.75
    //   ball condition    0.89
    //   η × wear          0.667
    //   hood angle bias   +0.0°  (slo-mo offset)
    //   wheel radius      0.0508 m
    //   drag              on  (Cd=0.50, m=0.215 kg, d=0.150 m)
    public static void loadLUTSolved() {
        minShootDistance = 1.743;
        maxShootDistance = 6.200;

        shootingFlywheelVelocityMap.clear();
        shootingHoodAngleMap.clear();
        shootingTimeOfFlightMap.clear();

        shootingFlywheelVelocityMap.put(1.743, 10.89);
        shootingFlywheelVelocityMap.put(2.086, 11.13);
        shootingFlywheelVelocityMap.put(2.429, 10.57);
        shootingFlywheelVelocityMap.put(2.771, 10.95);
        shootingFlywheelVelocityMap.put(3.114, 11.33);
        shootingFlywheelVelocityMap.put(3.457, 11.74);
        shootingFlywheelVelocityMap.put(3.800, 12.06);
        shootingFlywheelVelocityMap.put(4.143, 12.42);
        shootingFlywheelVelocityMap.put(4.486, 12.77);
        shootingFlywheelVelocityMap.put(4.829, 13.12);
        shootingFlywheelVelocityMap.put(5.171, 13.49);
        shootingFlywheelVelocityMap.put(5.514, 13.86);
        shootingFlywheelVelocityMap.put(5.857, 14.19);
        shootingFlywheelVelocityMap.put(6.200, 14.59);

        shootingHoodAngleMap.put(1.743, Rotation2d.fromDegrees(73));
        shootingHoodAngleMap.put(2.086, Rotation2d.fromDegrees(71));
        shootingHoodAngleMap.put(2.429, Rotation2d.fromDegrees(61));
        shootingHoodAngleMap.put(2.771, Rotation2d.fromDegrees(59));
        shootingHoodAngleMap.put(3.114, Rotation2d.fromDegrees(58));
        shootingHoodAngleMap.put(3.457, Rotation2d.fromDegrees(58));
        shootingHoodAngleMap.put(3.800, Rotation2d.fromDegrees(56));
        shootingHoodAngleMap.put(4.143, Rotation2d.fromDegrees(55));
        shootingHoodAngleMap.put(4.486, Rotation2d.fromDegrees(54));
        shootingHoodAngleMap.put(4.829, Rotation2d.fromDegrees(53));
        shootingHoodAngleMap.put(5.171, Rotation2d.fromDegrees(53));
        shootingHoodAngleMap.put(5.514, Rotation2d.fromDegrees(53));
        shootingHoodAngleMap.put(5.857, Rotation2d.fromDegrees(52));
        shootingHoodAngleMap.put(6.200, Rotation2d.fromDegrees(53));

        shootingTimeOfFlightMap.put(1.743, 1.110);
        shootingTimeOfFlightMap.put(2.086, 1.125);
        shootingTimeOfFlightMap.put(2.429, 0.894);
        shootingTimeOfFlightMap.put(2.771, 0.937);
        shootingTimeOfFlightMap.put(3.114, 0.975);
        shootingTimeOfFlightMap.put(3.457, 1.035);
        shootingTimeOfFlightMap.put(3.800, 1.039);
        shootingTimeOfFlightMap.put(4.143, 1.066);
        shootingTimeOfFlightMap.put(4.486, 1.090);
        shootingTimeOfFlightMap.put(4.829, 1.111);
        shootingTimeOfFlightMap.put(5.171, 1.157);
        shootingTimeOfFlightMap.put(5.514, 1.201);
        shootingTimeOfFlightMap.put(5.857, 1.216);
        shootingTimeOfFlightMap.put(6.200, 1.285);

        // Envelope band — min/max commanded wheel m/s that still scores at
        // each distance. Used by the distance-dependent ready gate.
        hasEnvelopeBand = true;
        shootingFlywheelVelocityCloseMap.put(1.743, 8.66);
        shootingFlywheelVelocityCloseMap.put(2.086, 9.08);
        shootingFlywheelVelocityCloseMap.put(2.429, 9.32);
        shootingFlywheelVelocityCloseMap.put(2.771, 9.65);
        shootingFlywheelVelocityCloseMap.put(3.114, 10.02);
        shootingFlywheelVelocityCloseMap.put(3.457, 10.40);
        shootingFlywheelVelocityCloseMap.put(3.800, 10.78);
        shootingFlywheelVelocityCloseMap.put(4.143, 11.16);
        shootingFlywheelVelocityCloseMap.put(4.486, 11.54);
        shootingFlywheelVelocityCloseMap.put(4.829, 11.91);
        shootingFlywheelVelocityCloseMap.put(5.171, 12.29);
        shootingFlywheelVelocityCloseMap.put(5.514, 12.66);
        shootingFlywheelVelocityCloseMap.put(5.857, 13.02);
        shootingFlywheelVelocityCloseMap.put(6.200, 13.40);

        shootingFlywheelVelocityFarMap.put(1.743, 11.11);
        shootingFlywheelVelocityFarMap.put(2.086, 11.33);
        shootingFlywheelVelocityFarMap.put(2.429, 10.70);
        shootingFlywheelVelocityFarMap.put(2.771, 11.08);
        shootingFlywheelVelocityFarMap.put(3.114, 11.46);
        shootingFlywheelVelocityFarMap.put(3.457, 11.88);
        shootingFlywheelVelocityFarMap.put(3.800, 12.19);
        shootingFlywheelVelocityFarMap.put(4.143, 12.54);
        shootingFlywheelVelocityFarMap.put(4.486, 12.89);
        shootingFlywheelVelocityFarMap.put(4.829, 13.24);
        shootingFlywheelVelocityFarMap.put(5.171, 13.61);
        shootingFlywheelVelocityFarMap.put(5.514, 13.98);
        shootingFlywheelVelocityFarMap.put(5.857, 14.31);
        shootingFlywheelVelocityFarMap.put(6.200, 14.71);
    }
}
