
package org.steelhawks;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj CenterPath = new ChoreoTraj(
	    "CenterPath",
	    OptionalInt.empty(),
	    4.79161,
	    new Pose2d(3.539, 0.66, Rotation2d.fromRadians(1.571)),
	    new Pose2d(2.581, 0.784, Rotation2d.fromRadians(1.597))
	);
	public static final ChoreoTraj CenterPath$0 = new ChoreoTraj(
	    "CenterPath",
	    OptionalInt.of(0),
	    2.2359,
	    new Pose2d(3.539, 0.66, Rotation2d.fromRadians(1.571)),
	    new Pose2d(7.601, 2.828, Rotation2d.fromRadians(-3.088))
	);
	public static final ChoreoTraj CenterPath$1 = new ChoreoTraj(
	    "CenterPath",
	    OptionalInt.of(1),
	    2.5557100000000004,
	    new Pose2d(7.601, 2.828, Rotation2d.fromRadians(-3.088)),
	    new Pose2d(2.581, 0.784, Rotation2d.fromRadians(1.597))
	);
	public static final ChoreoTraj FourMeterSpinTest = new ChoreoTraj(
	    "FourMeterSpinTest",
	    OptionalInt.empty(),
	    2.22895,
	    new Pose2d(1, 0.537, Rotation2d.fromRadians(0)),
	    new Pose2d(5, 0.537, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj FourMeterTest = new ChoreoTraj(
	    "FourMeterTest",
	    OptionalInt.empty(),
	    2.23064,
	    new Pose2d(1, 0.537, Rotation2d.fromRadians(0)),
	    new Pose2d(5, 0.537, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj LRebound = new ChoreoTraj(
	    "LRebound",
	    OptionalInt.empty(),
	    9.5246,
	    new Pose2d(4.429, 7.436, Rotation2d.fromRadians(0)),
	    new Pose2d(3.5, 7.436, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj LRebound$0 = new ChoreoTraj(
	    "LRebound",
	    OptionalInt.of(0),
	    4.53341,
	    new Pose2d(4.429, 7.436, Rotation2d.fromRadians(0)),
	    new Pose2d(3.5, 7.436, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj LRebound$1 = new ChoreoTraj(
	    "LRebound",
	    OptionalInt.of(1),
	    4.99119,
	    new Pose2d(3.5, 7.436, Rotation2d.fromRadians(0)),
	    new Pose2d(3.5, 7.436, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj MiddleDepotAuton = new ChoreoTraj(
	    "MiddleDepotAuton",
	    OptionalInt.empty(),
	    4.77722,
	    new Pose2d(3.577, 4.021, Rotation2d.fromRadians(3.142)),
	    new Pose2d(2.818, 4.97, Rotation2d.fromRadians(-2.451))
	);
	public static final ChoreoTraj MiddleDepotAuton$0 = new ChoreoTraj(
	    "MiddleDepotAuton",
	    OptionalInt.of(0),
	    0.5371,
	    new Pose2d(3.577, 4.021, Rotation2d.fromRadians(3.142)),
	    new Pose2d(2.818, 4.97, Rotation2d.fromRadians(-2.451))
	);
	public static final ChoreoTraj MiddleDepotAuton$1 = new ChoreoTraj(
	    "MiddleDepotAuton",
	    OptionalInt.of(1),
	    4.24012,
	    new Pose2d(2.818, 4.97, Rotation2d.fromRadians(-2.451)),
	    new Pose2d(2.818, 4.97, Rotation2d.fromRadians(-2.451))
	);
	public static final ChoreoTraj MiddleDepotAuton2 = new ChoreoTraj(
	    "MiddleDepotAuton2",
	    OptionalInt.empty(),
	    4.38012,
	    new Pose2d(3.577, 4.021, Rotation2d.fromRadians(3.142)),
	    new Pose2d(2.818, 4.97, Rotation2d.fromRadians(-2.451))
	);
	public static final ChoreoTraj MiddleDepotAuton2$0 = new ChoreoTraj(
	    "MiddleDepotAuton2",
	    OptionalInt.of(0),
	    0.55155,
	    new Pose2d(3.577, 4.021, Rotation2d.fromRadians(3.142)),
	    new Pose2d(2.818, 4.97, Rotation2d.fromRadians(-2.451))
	);
	public static final ChoreoTraj MiddleDepotAuton2$1 = new ChoreoTraj(
	    "MiddleDepotAuton2",
	    OptionalInt.of(1),
	    3.82857,
	    new Pose2d(2.818, 4.97, Rotation2d.fromRadians(-2.451)),
	    new Pose2d(2.818, 4.97, Rotation2d.fromRadians(-2.451))
	);
	public static final ChoreoTraj NotSoOPAuton = new ChoreoTraj(
	    "NotSoOPAuton",
	    OptionalInt.empty(),
	    15.93516,
	    new Pose2d(4.429, 0.633, Rotation2d.fromRadians(0)),
	    new Pose2d(7.882, 5.08, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj NotSoOPAuton$0 = new ChoreoTraj(
	    "NotSoOPAuton",
	    OptionalInt.of(0),
	    5.28219,
	    new Pose2d(4.429, 0.633, Rotation2d.fromRadians(0)),
	    new Pose2d(2.958, 2.849, Rotation2d.fromRadians(2.521))
	);
	public static final ChoreoTraj NotSoOPAuton$1 = new ChoreoTraj(
	    "NotSoOPAuton",
	    OptionalInt.of(1),
	    6.75489,
	    new Pose2d(2.958, 2.849, Rotation2d.fromRadians(2.521)),
	    new Pose2d(2.958, 2.849, Rotation2d.fromRadians(2.521))
	);
	public static final ChoreoTraj NotSoOPAuton$2 = new ChoreoTraj(
	    "NotSoOPAuton",
	    OptionalInt.of(2),
	    3.89808,
	    new Pose2d(2.958, 2.849, Rotation2d.fromRadians(2.521)),
	    new Pose2d(7.882, 5.08, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj OPAuton = new ChoreoTraj(
	    "OPAuton",
	    OptionalInt.empty(),
	    25.12839,
	    new Pose2d(4.429, 0.633, Rotation2d.fromRadians(0)),
	    new Pose2d(7.882, 5.08, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj OPAuton$0 = new ChoreoTraj(
	    "OPAuton",
	    OptionalInt.of(0),
	    5.1959,
	    new Pose2d(4.429, 0.633, Rotation2d.fromRadians(0)),
	    new Pose2d(2.837, 2.553, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj OPAuton$1 = new ChoreoTraj(
	    "OPAuton",
	    OptionalInt.of(1),
	    6.06021,
	    new Pose2d(2.837, 2.553, Rotation2d.fromRadians(3.142)),
	    new Pose2d(3.937, 0.633, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj OPAuton$2 = new ChoreoTraj(
	    "OPAuton",
	    OptionalInt.of(2),
	    4.917639999999999,
	    new Pose2d(3.937, 0.633, Rotation2d.fromRadians(0)),
	    new Pose2d(2.837, 2.553, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj OPAuton$3 = new ChoreoTraj(
	    "OPAuton",
	    OptionalInt.of(3),
	    6.060170000000003,
	    new Pose2d(2.837, 2.553, Rotation2d.fromRadians(3.142)),
	    new Pose2d(3.937, 0.633, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj OPAuton$4 = new ChoreoTraj(
	    "OPAuton",
	    OptionalInt.of(4),
	    2.8944699999999983,
	    new Pose2d(3.937, 0.633, Rotation2d.fromRadians(0)),
	    new Pose2d(7.882, 5.08, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj RDoubleRebound = new ChoreoTraj(
	    "RDoubleRebound",
	    OptionalInt.empty(),
	    10.86229,
	    new Pose2d(4.429, 0.633, Rotation2d.fromRadians(0)),
	    new Pose2d(3, 0.643, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj RDoubleRebound$0 = new ChoreoTraj(
	    "RDoubleRebound",
	    OptionalInt.of(0),
	    5.23922,
	    new Pose2d(4.429, 0.633, Rotation2d.fromRadians(0)),
	    new Pose2d(3, 0.643, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RDoubleRebound$1 = new ChoreoTraj(
	    "RDoubleRebound",
	    OptionalInt.of(1),
	    5.623069999999999,
	    new Pose2d(3, 0.643, Rotation2d.fromRadians(0)),
	    new Pose2d(3, 0.643, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj RRebound = new ChoreoTraj(
	    "RRebound",
	    OptionalInt.empty(),
	    9.44284,
	    new Pose2d(4.429, 0.633, Rotation2d.fromRadians(0)),
	    new Pose2d(4.394, 0.643, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RRebound$0 = new ChoreoTraj(
	    "RRebound",
	    OptionalInt.of(0),
	    4.38167,
	    new Pose2d(4.429, 0.633, Rotation2d.fromRadians(0)),
	    new Pose2d(5.602, 0.643, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RRebound$1 = new ChoreoTraj(
	    "RRebound",
	    OptionalInt.of(1),
	    0.5274600000000005,
	    new Pose2d(5.602, 0.643, Rotation2d.fromRadians(0)),
	    new Pose2d(4.394, 0.643, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RRebound$2 = new ChoreoTraj(
	    "RRebound",
	    OptionalInt.of(2),
	    4.006189999999999,
	    new Pose2d(4.394, 0.643, Rotation2d.fromRadians(0)),
	    new Pose2d(5.602, 0.643, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RRebound$3 = new ChoreoTraj(
	    "RRebound",
	    OptionalInt.of(3),
	    0.5275200000000009,
	    new Pose2d(5.602, 0.643, Rotation2d.fromRadians(0)),
	    new Pose2d(4.394, 0.643, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RRebound_Bump = new ChoreoTraj(
	    "RRebound_Bump",
	    OptionalInt.empty(),
	    9.1246,
	    new Pose2d(4.429, 0.633, Rotation2d.fromRadians(0)),
	    new Pose2d(0.451, 0.643, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj RRebound_Bump$0 = new ChoreoTraj(
	    "RRebound_Bump",
	    OptionalInt.of(0),
	    4.51196,
	    new Pose2d(4.429, 0.633, Rotation2d.fromRadians(0)),
	    new Pose2d(3.255, 2.453, Rotation2d.fromRadians(0.785))
	);
	public static final ChoreoTraj RRebound_Bump$1 = new ChoreoTraj(
	    "RRebound_Bump",
	    OptionalInt.of(1),
	    3.6230200000000004,
	    new Pose2d(3.255, 2.453, Rotation2d.fromRadians(0.785)),
	    new Pose2d(3.611, 0.643, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj RRebound_Bump$2 = new ChoreoTraj(
	    "RRebound_Bump",
	    OptionalInt.of(2),
	    0.9896199999999986,
	    new Pose2d(3.611, 0.643, Rotation2d.fromRadians(3.142)),
	    new Pose2d(0.451, 0.643, Rotation2d.fromRadians(3.142))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("CenterPath", CenterPath),
		Map.entry("CenterPath$0", CenterPath$0),
		Map.entry("CenterPath$1", CenterPath$1),
		Map.entry("FourMeterSpinTest", FourMeterSpinTest),
		Map.entry("FourMeterTest", FourMeterTest),
		Map.entry("LRebound", LRebound),
		Map.entry("LRebound$0", LRebound$0),
		Map.entry("LRebound$1", LRebound$1),
		Map.entry("MiddleDepotAuton", MiddleDepotAuton),
		Map.entry("MiddleDepotAuton$0", MiddleDepotAuton$0),
		Map.entry("MiddleDepotAuton$1", MiddleDepotAuton$1),
		Map.entry("MiddleDepotAuton2", MiddleDepotAuton2),
		Map.entry("MiddleDepotAuton2$0", MiddleDepotAuton2$0),
		Map.entry("MiddleDepotAuton2$1", MiddleDepotAuton2$1),
		Map.entry("NotSoOPAuton", NotSoOPAuton),
		Map.entry("NotSoOPAuton$0", NotSoOPAuton$0),
		Map.entry("NotSoOPAuton$1", NotSoOPAuton$1),
		Map.entry("NotSoOPAuton$2", NotSoOPAuton$2),
		Map.entry("OPAuton", OPAuton),
		Map.entry("OPAuton$0", OPAuton$0),
		Map.entry("OPAuton$1", OPAuton$1),
		Map.entry("OPAuton$2", OPAuton$2),
		Map.entry("OPAuton$3", OPAuton$3),
		Map.entry("OPAuton$4", OPAuton$4),
		Map.entry("RDoubleRebound", RDoubleRebound),
		Map.entry("RDoubleRebound$0", RDoubleRebound$0),
		Map.entry("RDoubleRebound$1", RDoubleRebound$1),
		Map.entry("RRebound", RRebound),
		Map.entry("RRebound$0", RRebound$0),
		Map.entry("RRebound$1", RRebound$1),
		Map.entry("RRebound$2", RRebound$2),
		Map.entry("RRebound$3", RRebound$3),
		Map.entry("RRebound_Bump", RRebound_Bump),
		Map.entry("RRebound_Bump$0", RRebound_Bump$0),
		Map.entry("RRebound_Bump$1", RRebound_Bump$1),
		Map.entry("RRebound_Bump$2", RRebound_Bump$2)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
