// LUT generator. Sweeps distance, runs the envelope solver at each step, and
// emits a table the team can paste straight into ShooterStructure.java.
//
// Output mirrors the existing loadLUTHard / loadLUTSoft signature:
//   shootingFlywheelVelocityMap.put(<dist>, <exit m/s>)
//   shootingHoodAngleMap.put(<dist>, Rotation2d.fromDegrees(<deg>))
//   shootingTimeOfFlightMap.put(<dist>, <seconds>)
//
// Note: their LUT stores apparent EXIT velocity (m/s) not motor RPS. The
// rps↔mps mapping happens elsewhere in the motor command path (it's near
// linear per the team's notes, with η_slip baked in). So this generator emits
// the same units the existing code consumes.

import { solveEnvelope, pickOptimal } from "./solver.js";
import { simulateToGoalY } from "./physics.js";
import { wheelRpsForBall, wheelMpsForBall } from "./slip.js";

/**
 * @param {{distMin:number, distMax:number, steps:number}} sweep
 * @param {object} geomBase  geometry without `distance`
 * @param {object} search
 * @param {object} env
 * @param {object} slip
 * @param {number} wheelRadius
 */
export function generateLUT(sweep, geomBase, search, env, slip, wheelRadius, angleBiasDeg = 0) {
  const distances = [];
  const dStep = (sweep.distMax - sweep.distMin) / (sweep.steps - 1);
  for (let i = 0; i < sweep.steps; i++) {
    distances.push(sweep.distMin + i * dStep);
  }

  const rows = [];
  for (const d of distances) {
    const geom = { ...geomBase, distance: d };
    const envSolve = solveEnvelope(geom, search, env);
    const opt = pickOptimal(envSolve);
    if (!opt) {
      rows.push({ distance: d, ok: false });
      continue;
    }
    // Time of flight: simulate the optimal and grab the goal-Y crossing time.
    const tofRes = simulateToGoalY(opt.v0, opt.thetaRad, {
      ...env, x0: 0, y0: geom.launchZ, stopX: envSolve.geom.xFar + 1.0,
    }, geom.hubZ);
    const revPerSec = wheelRpsForBall(opt.v0, slip, wheelRadius);
    const wheelMps = wheelMpsForBall(opt.v0, slip);
    const physDeg = opt.thetaRad * 180 / Math.PI;
    rows.push({
      distance: d,
      ok: true,
      physDeg,                   // physics-optimal launch angle
      hoodDeg: physDeg + angleBiasDeg, // what the hood motor should target
      exitMps: opt.v0,
      wheelMps,
      wheelRevPerSec: revPerSec,
      wheelRadPerSec: revPerSec * 2 * Math.PI,
      tof: tofRes.t,
    });
  }
  return rows;
}

/** Emit Java code matching ShooterStructure.loadLUT* shape. */
export function toJava(name, rows) {
  const ok = rows.filter(r => r.ok);
  if (ok.length === 0) return "// no solutions found across the requested range";
  const dMin = ok[0].distance;
  const dMax = ok[ok.length - 1].distance;
  const f3 = n => n.toFixed(3);
  const f2 = n => n.toFixed(2);
  const f0 = n => n.toFixed(0);

  const lines = [];
  lines.push(`// Generated by shot-solver. Values are COMMANDED wheel-surface m/s`);
  lines.push(`// (ideal ball exit ÷ η_slip · wear). If you re-tune the slip slider,`);
  lines.push(`// regenerate — the offset is uniform across distances.`);
  lines.push(`public static void ${name}() {`);
  lines.push(`    minShootDistance = ${f3(dMin)};`);
  lines.push(`    maxShootDistance = ${f3(dMax)};`);
  lines.push(``);
  lines.push(`    switchLUT(true);`);
  lines.push(`    shootingFlywheelVelocityMap.clear();`);
  lines.push(`    shootingHoodAngleMap.clear();`);
  lines.push(`    shootingTimeOfFlightMap.clear();`);
  lines.push(``);
  for (const r of ok) {
    lines.push(`    shootingFlywheelVelocityMap.put(${f3(r.distance)}, ${f2(r.wheelMps)});`);
  }
  lines.push(``);
  for (const r of ok) {
    lines.push(`    shootingHoodAngleMap.put(${f3(r.distance)}, Rotation2d.fromDegrees(${f0(r.hoodDeg)}));`);
  }
  lines.push(``);
  for (const r of ok) {
    const tof = r.tof != null ? r.tof.toFixed(3) : "0.000";
    lines.push(`    shootingTimeOfFlightMap.put(${f3(r.distance)}, ${tof});`);
  }
  lines.push(`}`);
  return lines.join("\n");
}

/** Compact preview table for the UI. */
export function toPreview(rows) {
  const header = "dist(m)   hood°   ball m/s   wheel m/s   rev/s   rad/s   TOF(s)";
  const sep    = "────────────────────────────────────────────────────────────────";
  const body = rows.map(r => {
    if (!r.ok) return `${r.distance.toFixed(3).padStart(7)}   —      —          —          —      —       —`;
    return [
      r.distance.toFixed(3).padStart(7),
      r.hoodDeg.toFixed(1).padStart(5),
      r.exitMps.toFixed(2).padStart(8),
      r.wheelMps.toFixed(2).padStart(9),
      r.wheelRevPerSec.toFixed(1).padStart(5),
      r.wheelRadPerSec.toFixed(1).padStart(6),
      (r.tof ?? 0).toFixed(3).padStart(6),
    ].join("   ");
  }).join("\n");
  return [header, sep, body].join("\n");
}
